### ISSUE TITLE
请问我下载hexo-generator-search 配置config 后页面也不显示 搜索页面

### ISSUE THREAD

**Issue by fanyibo2009** [Pcrab/hexo-theme-quark#3]

**Comment by fanyibo2009** [comment]
目前最喜欢的主题哈哈哈

**Comment by Pcrab** [comment]
要新建一个叫 search 的 page，然后再把它的 layout 改成 search

**Comment by fanyibo2009** [comment]
> 要新建一个叫 search 的 page，然后再把它的 layout 改成 search

已解决，还以为是_config.yml 中 "path: search.xml" 的路径设置不对，有些博客说要配置为"path: ./public/search.xml"
